### ISSUE TITLE
Check that configured ports are reachable

### ISSUE THREAD

**Issue by treygriffith** [sparkswap/broker#322]
Configuration on a broker daemon requires that a user is reachable via their `EXTERNAL_ADDRESS` and several ports (10113, 10114, and perhaps 27492 for the Broker RPC).

We should add a utility that runs on startup that ensures that the ports are reachable externally and creates a warning if they are not.

**Comment by dannypaz** [comment]
@treygriffith Myself and @mdasif are going to work through this one
